### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by zabojad** [react-native-community/react-native-progress-bar-android#110]
We had quite a few important PRs merged lately (new arch support for example). Could be great to make a new release, nope?

**Comment by kyadalu1** [comment]
https://www.youtube.com/watch?v=4CfbWs1Gl-A

**Comment by sudhanva-games24x7** [comment]
+1

**Comment by d4rky-pl** [comment]
bump 2 years later

**Comment by dprevost-LMI** [comment]
Just found out that the one in `react-native` version is deprecated + crashes on newArch, and the replacement is 3 years old, 😒. 


```
(NOBRIDGE) ERROR Error: Exception in HostFunction: java.lang.NullPointerException: Parameter specified as non-null is null: method com.facebook.react.views.progressbar.ReactProgressBarViewManager.measure, parameter localData
at com.facebook.react.views.progressbar.ReactProgressBarViewManager.measure(Unknown Source:13)
at com.facebook.react.fabric.mounting.MountingManager.measure(MountingManager.java:372)
at com.facebook.react.fabric.FabricUIManager.measure(FabricUIManager.java:575)
at com.facebook.react.fabric.FabricUIManager.measure(FabricUIManager.java:519)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at java.lang.Thread.run(Thread.java:1119)
```
